CREATE DATABASE IF NOT EXISTS `beable`;

USE `beable`;

CREATE TABLE IF NOT EXISTS `grades` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(64) NOT NULL,
  `credits` INT NOT NULL
) ENGINE=InnoDB;
